SELECT
    e.EMP_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    d.DEPARTMENT_NAME,
    COUNT(e2.EMP_ID) AS YOUNGER_EMPLOYEES_COUNT
FROM EMPLOYEE e
         JOIN DEPARTMENT d ON e.DEPARTMENT = d.DEPARTMENT_ID
         LEFT JOIN EMPLOYEE e2
                   ON e.DEPARTMENT = e2.DEPARTMENT
                       AND TIMESTAMPDIFF(YEAR, e2.DOB, CURDATE()) < TIMESTAMPDIFF(YEAR, e.DOB, CURDATE())
GROUP BY e.EMP_ID, e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_NAME
ORDER BY e.EMP_ID DESC;
